version: '3.9'

services:
  hamy-user-auth:
    container_name: hamy-user-auth
    build: .
    networks:
      - hamy-network
    restart: on-failure
    env_file:
      - .env
    environment:
      - LOGFIRE_TOKEN
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - hamy-auth-postgres

  hamy-auth-postgres:
    image: postgres:16.1
    container_name: hamy-auth-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    networks:
      - hamy-network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: on-failure
    stdin_open: true
    tty: true


networks:
  hamy-network:
    external: true

volumes:
  postgres_data: